### ISSUE TITLE
feat: Simplify site for Cortex.cpp

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/cortex.so#197]
## Goal

- Simplify website for Cortex.cpp
- Remove incorrect directions
- Remove value propositions that are not ready yet

## Tasklist

- Keep existing components (they will come in useful later on)

![Image](https://github.com/user-attachments/assets/73af964a-36ba-4db5-a8af-222fc764b1b5)

**Comment by urmauur** [comment]
@dan-homebrew can I get clarify?, whether we want to get data from GitHub or Manually add changelog like Jan every release?

**Comment by dan-homebrew** [comment]
> @dan-homebrew can I get clarify?, whether we want to get data from GitHub or Manually add changelog like Jan every release?

@urmauur We should use client-side data from Github as much as possible, and fail gently if the request errors out.

**Comment by urmauur** [comment]
@dan-homebrew could you check this ticket? The PR is already open https://github.com/janhq/cortex.so/pull/199
