### ISSUE TITLE
docs: README edits

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/cortex.so#198]
## Goal 

- Simplify README
- Make corrections
- Link to Docs where appropriate

### Structure

I would like to make a quick modification to the structure

```
## Overview

- Combine "About" and "Installation"

## Quickstart

## Built-in Model Library

## Alternate Installation Methods

### Beta & Nightly 

### Build from Source
```

## About Section

- Let's combine the "About" and "Installation" sections
- We should include links only for the Stable release
- We prefer "Download" link (vs. "cortexcpp.exe" filename)

You will need to ask @hiento09 for the exact Installers we are providing:
- Mac might be universal
- There might be a Network installer (i.e. pulls at install-time)

## Quickstart

I would like to have a more comprehensive Quickstart, that covers our most common scenario:

```
# Start server
cortex start

# Pulls models
cortex pull <huggingface>
cortex pull llama3.1         # From our curated built-in model library

# Run and use model
cortex run llama3.1 
cortex chat llama3.1
```

Guide the user to use the API server
- Cortex server is running at localhost:3928
- make API request to cortex.cpp
- Guide user that they can use this with many integrations
```
curl /chat/completions
```

Walk the user to stop the model, and the server
```
cortex stop model
cortex stop
```

Possible additional things to weave in (we can discuss in comments):
- .cortexrc
- Model folder (after pull, see where files are stored)
- Editing a model.yaml

### Built-in Model Library

I would like to combine all 3 tables into one, simplified version

| Model    | llama.cpp<br >`:gguf` | TensorRT<br >`:tensorrt` | ONNXRuntime<br >`:onnx` | Command             |
|----------|-----------------------|--------------------------|-------------------------|---------------------|
| llama3.1 | ✅                     | ✅                        | ✅                       | cortex run llama3.1 |
| mistral  | ✅                     | ✅                        | ✅                       | cortex run mistral  |
| qwen2    | ✅                     |                          |                         | cortex run qwen2    |

### CLI Commands

- I think we should just link to the CLI section in https://cortex.so

### REST API

- I think we should link to the API page https://cortex.so

## Uninstall

- We should have uninstall instructions here
- Check with @hiento09 to make sure all details are captured

### Alternate Installation

- We should move Beta, and Nightly to this section (can re-use the table)
- We should move the Build from Source to this section

**Comment by irfanpena** [comment]
@dan-homebrew I think for the following we should just detail them in the docs rather than the readme, as I think this requires a lot of explanation as the readme should just be a simple docs that really introduces what is Cortex.cpp:
- .cortexrc
- Editing a model.yaml
