### ISSUE TITLE
feat: update docs cover image

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex.so#47]
![image](https://github.com/janhq/cortex-web/assets/69952136/aa505958-93ff-492c-8d23-13fffc5a1a4b)

New Commands: 

```bash
cortex run llama3:gguf
cortex run llama3:onnx
cortex run llama3:tensorrt-llm
```

Bonus points, if you can show that the cli is open ai compatible.
/models ==> cortex models list
/chat/completes ==> cortex models chat
/audio ==> cortex audio

**Comment by imtuyethan** [comment]
deprecated
