### ISSUE TITLE
docs: Cortex CLI Support Remote Model

### ISSUE THREAD

**Issue by Van-QA** [janhq/cortex.so#66]
![image](https://github.com/janhq/cortex-web/assets/64197333/bf1bc3b7-aeac-4cba-a84b-8896fb5ab9a9)
` cortex run gpt-3.5-turbo`

**Comment by Van-QA** [comment]
No need to work on it at the moment. Creating tickets for tracking purposes only, Thank you.

**Comment by dan-homebrew** [comment]
This is deprecated, as Remote APIs are a Jan concern (not a cortex.cpp concern)
