### ISSUE TITLE
docs: refactor installation guide

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex.so#68]
Let's separate `installation` from `requirements`. 
The current hardware/install guides are a bit all over the place and conflate the two

Design: 
1. Guides should be driven by the user's OS. This is the starting point for most people. Like "ok I have a windows with x cpu, and y gpus, what do i need"

2. Requirements guide should address dependencies, i.e. if users wanted to chck if they have proper deps. This is because we auto-install things now, we need to be transparent about what exact requirements are.

**Suggested refactoring**
---

## Installation

Refactor `Prerequisites` section into Requirements pages.

Everything else, keep as is.

---

### Hardware Requirements
CPU, Disk, RAM, all that (in tabs)

Should cover stuff like: 
- cpu size, cpu skus, instruction sets
- disk size, etc.

### OS Requirements
Mac, Windows, LInux (in tabs)

Should cover stuff like:
- os version
- npm version, etc.

### GPU Requirements
NVIDIA, AMD, Silicon, Snapdragon NPU, etc. (in tabs)

Should cover stuff like:
- checking driver and sdk deps & versions
- install guide (with verification instructions)
	- gpu driver
	- cuda toolkit
	- msi
	- msisdk

**Comment by irfanpena** [comment]
Added the first cut of the requirements page. Will keep the issue up for tracking

**Comment by irfanpena** [comment]
This is ticket outdated since the final decision was to put the prerequisite back to each page at the end of the page
