### ISSUE TITLE
docs: update Cortex Overview. Improve product positioning

### ISSUE THREAD

**Issue by 0xSage** [janhq/cortex.so#82]
i.e. 

why devs would want cortex: 
Model routing: Offline features for their application
Stop paying openai bill
Private solution for their users
Scales: cortex works from PC to a dc cluster
Fast
portable: corss device
offline

**Comment by dan-homebrew** [comment]
Deprecated as part of Cortex Platform. Superseded by https://github.com/janhq/cortex.cpp/issues/1148
